### ISSUE TITLE
[Feature Request] Enhanced @when trigger for number items

### ISSUE THREAD

**Issue by Andirs55** [OH-Jython-Scripters/openhab2-jython#46]
Hello, i would like the idea to enhance the @when trigger for number items so that the rule only triggers when a certain condition is met.

For example:
```
@when("Item NumberItem changed to <10")
@when("Item NumberItem changed to >=12")
@when("Item NumberItem changed to ==15")
@when("Item NumberItem changed to 10-15") # >=10 and <=15
```
One of my use cases is a warning if a room gets to moist. At the moment the rule has to trigger every time and check of the condition is met like this:
```
@rule("rNotificationRoomTooMoist")
@when("Descendent of gUnisenHum changed")
def rNotificationRoomTooMoist(event):
	if event.itemState.floatValue() > 80.0:
		log.warn("Room too moist: " + event.itemName)
```

In my opinion this would be more elegant and furthermore it does not flood the log that much:
```
@rule("rNotificationRoomTooMoist")
@when("Descendent of gUnisenHum changed to > 80.0")
def rNotificationRoomTooMoist(event):
	log.warn("Room too moist: " + event.itemName)
```

Thanks a lot :)

**Comment by openhab-5iver** [comment]
This is very similar to the request to add conditions :smile:... code-wise, it's essentially the same. The current triggers provided in ESH (changed, received update, received command) require states. So, you'd end up having the same triggers, but the logic would need to be applied through conditions rather than in the rule. You seem to be really swamped with logs! Check my suggestion in #47. I'll close this one, since it really is the same 47.
