### ISSUE TITLE
ItemStateChangeTrigger incompatible changes

### ISSUE THREAD

**Issue by HolgerHees** [OH-Jython-Scripters/openhab2-jython#57]
before I create a pull request I want to ask if we can revert the __init__ parameter order of the class ItemStateChangeTrigger

in the past it was like
```
class ItemStateChangeTrigger(Trigger):
    def __init__(self, itemName, state=None, triggerName=None, previousState=None):
```
now it is
```
class ItemStateChangeTrigger(Trigger):
    def __init__(self, itemName, previousState=None, state=None, triggerName=None):
```
was this a mistake or a wanted change. I ask because I have modify > 50 places.

**Comment by openhab-5iver** [comment]
> was this a mistake or a wanted change

It was wanted, but for no reason other than to put the arguments in a better order, and consistent with the others. I never thought of it as a breaking change, and that anyone would have been using the kwargs as positional arguments, since I always specify the name for kwargs. I'd be afraid to change it now though, in case it might break for other people. Sorry about this, and for the effort you'll need to put in. It'll be worth it!

And if you're having to make these changes in your rules, you might as well use the decorators! :wink:
