### ISSUE TITLE
Add scale transformation in transformation setting of addons.cfg, not misc setting

### ISSUE THREAD

**Issue by ScottKinSF** [OH-Jython-Scripters/openhab2-jython#65]
In the python doc REQUIRES section of owm_daily_forecast.py, the text describing where to add the `scale` transformation service is wrong, it should be added to the `transformation` setting, not `misc` in addons.cfg.

**Comment by openhab-5iver** [comment]
Thank you... fixed! I [also just added](https://github.com/OH-Jython-Scripters/openhab2-jython/pull/67) Forecast_Temperature_High_X and Forecast_Temperature_Low_X.

Have you tried using this? There's someone in the forum [reporting an error](https://community.openhab.org/t/openweathermap-daily-forecast-using-the-free-api/62579/11?u=5iver), but it's working fine for me. Haven't heard from anyone else. 

Also, could you take a peak at #63 and #66 ? I really should have asked for a review before merging, but I wanted to get it the link fix out quick before more people tried using the script.

**Comment by openhab-5iver** [comment]
I've updated modules, so be sure to get them updated, but check those PRs first, since I renamed core.items.add to core.items.add_item. And the latest script should resolve the errors (you probably have Thing files). Glad you're playing with this! It's all working for me, and I'm working on a PR so that the group names will have the day of the week in them, and times in the Items.
